# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Set OS family dependent variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Set variable if autoscaling runner must be configured"
  ansible.builtin.set_fact:
    gitlab_runner_install_docker_machine: "{{ gitlab_runner_list | selectattr('executor', 'equalto', 'docker+machine') | list | length > 0 }}"
    gitlab_runner_install_autoscaler: "{{ gitlab_runner_list | selectattr('executor', 'equalto', 'docker-autoscaler') | list | length > 0 }}"

- name: "Check if directory /etc/gitlab-runner already exists"
  ansible.builtin.stat:
    path: "/etc/gitlab-runner"
  register: "gitlab_runner_dir"

- name: "Determine if this is an initial dry-run"
  ansible.builtin.set_fact:
    gitlab_runner_is_initial_dryrun: "{{ ansible_check_mode and not gitlab_runner_dir.stat.exists }}"

- name: "Include docker-machine tasks"
  ansible.builtin.include_tasks: install.docker-machine.yml
  when: "gitlab_runner_install_docker_machine"

- name: "Include installation tasks for Debian-like OS"
  ansible.builtin.include_tasks: install.debianlike.yml
  when: ansible_os_family == "Debian"

- name: "Include autoscaler install tasks"
  ansible.builtin.include_tasks: install.autoscaler-plugin.yml
  when: "gitlab_runner_install_autoscaler"

- name: "Include tasks to configure the system"
  ansible.builtin.include_tasks: configuration.yml

- name: "Ignition configuration must be generated before docker-machine init"
  ansible.builtin.meta: "flush_handlers"

- name: "Initialize docker-machine"
  ansible.builtin.include_tasks: "docker-machine-init.yml"
  when: "gitlab_runner_install_docker_machine"
  no_log: true
  loop: "{{ gitlab_runner_list }}"
  loop_control:
    loop_var: gitlab_runner

- name: "Slurp ignition json"
  ansible.builtin.slurp:
    src: "/etc/gitlab-runner/ignition.json"
  register: "ignition_json"
  when: "gitlab_runner_install_autoscaler"

- name: "Template config file"
  ansible.builtin.template:
    src: "config.toml.j2"
    dest: "{{ gitlab_runner_config_path }}"
    owner: "{{ gitlab_runner_config_owner | default('root') }}"
    group: "{{ gitlab_runner_config_group | default('root') }}"
    mode: "0600"
  notify: "Restart GitLab-Runner"
  no_log: true
  vars:
    ignition_content: "{{ ignition_json['content'] | b64decode }}"

- name: "Start GitLab-Runner"
  ansible.builtin.service:
    name: "gitlab-runner"
    state: "started"
  when: "not gitlab_runner_is_initial_dryrun"


...
